server=127.0.0.1:8080
server=127.0.0.1:8081
server=127.0.0.2:8080
server=127.0.0.2:8081



error_page=400.html
error_page=403.html
error_page=404.html
error_page=405.html
error_page=413.html
error_page=500.html
max_body_size=1048576



route=/,GET|POST,,,index.html,,false
route=/static,GET,,,,,true
route=/cgi-bin,GET|POST,,,script.cgi,/usr/bin/python,false
route=/upload,POST,,,,src/www/upload/server1,,false
route=/upload,POST,,,,src/www/upload/server2,,false
route=/files,GET,,,,,,false
